wandb_version: 1

alpha:
  value: 0.8
augmentation_scheme:
  value: randaugment
batch_size:
  value: 128
data_path:
  value: /kaggle/input/fii-atnn-2024-project-noisy-cifar-100/fii-atnn-2024-project-noisy-cifar-100
dataset:
  value: CIFAR100
eta_min:
  value: 1.0e-05
min_delta:
  value: 0.0001
model_name:
  value: eff_ns
momentum:
  value: 0.9
nesterov:
  value: 'True'
num_classes:
  value: 100
num_epochs:
  value: 50
optimizer_config:
  value:
    learning_rate: 0.001
    optimizer: adamw
patience:
  value: 5
patience_early_stopping:
  value: 10
pretrained:
  value: 'True'
scheduler:
  value: cosineannealinglr
stop_mode:
  value: max
t_0:
  value: 10
t_max:
  value: 100
t_mult:
  value: 2
use_cutmix:
  value: 'True'
use_mixup:
  value: 'False'
warmup:
  value: 3
weight_decay:
  value: 0.0005
