_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
batch_size:
    value: 128
learning_rate:
    value: 0.02
num_epochs:
    value: 250
optimizer:
    value: SGD
